services:
  app:
    build: .
    tty: true
    volumes:
     - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      - OW4_BASE_URL
      - OW5_BASE_URL
      - AUTH0_ISSUER
      - AUTH0_CLIENT_ID

  db:
    image: postgres:15.8
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "dev"]
      interval: 1s
      retries: 30
      timeout: 1s

volumes:
  postgres-data: null
