services:
  app:
    build: .
    tty: true
    volumes:
     - .:/app
    ports:
      - "8000:8000"
    command: [ "poetry", "run", "pytest", "--ignore=postgres-data", "--asyncio-mode=strict" ]

  db:
    image: postgres:11.3-alpine
    restart: unless-stopped
    volumes:
      - ./create-databases.sh:/docker-entrypoint-initdb.d/temp.sh
      - ./tests:/tests
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DEFAULT_DATABASE_NAME: db
      POSTGRES_PASSWORD: postgres
    logging:
      driver: none
    command: [ "-c", "fsync=off" ]

volumes:
  create-databases.sh: null
  tests: null
