version: '3.8'

services:
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: [ "poetry", "run", "uvicorn", "--reload", "--reload-dir", "app", "app.api.init_api:asgi_app", "--host", "0.0.0.0" ]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:11.3-alpine
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "dev"]
      interval: 1s
      retries: 30
      timeout: 1s

volumes:
  postgres-data: null