export { default as GitHubIcon } from "./GitHubIcon"
export { default as SlackIcon } from "./SlackIcon"
export { default as InstagramIcon } from "./InstagramIcon"
export { default as FacebookIcon } from "./FacebookIcon"
export { default as BriefcaseIcon } from "./BriefcaseIcon"
export { default as EnvelopeIcon } from "./EnvelopeIcon"
export { default as FileIcon } from "./FileIcon"
export { default as MobileIcon } from "./MobileIcon"
