# Generated by Django 3.0.3 on 2021-01-31 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('imageurl', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VineyardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('public', models.BooleanField(default=False)),
                ('rulesurl', models.URLField(max_length=256)),
                ('logourl', models.URLField(max_length=256)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verifiedDate', models.DateTimeField(null=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments_given', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment_system.VineyardGroup')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment_system.PunishmentType')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
