# Generated by Django 3.0.2 on 2020-04-19 12:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vineyarduser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='punishment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
