# Generated by Django 3.0.2 on 2020-03-01 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('punishment_system', '0002_punishmenttype_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='VineyardGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments_given', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment_system.VineyardGroup')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punishment_system.PunishmentType')),
            ],
        ),
    ]
