# Generated by Django 3.0.2 on 2020-03-01 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('punishment_system', '0003_punishment_vineyardgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='punishment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
