# Generated by Django 3.0.2 on 2020-03-01 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('punishment_system', '0004_punishment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
