# Generated by Django 3.0.2 on 2020-03-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment_system', '0006_auto_20200301_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vineyardgroup',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
