# Generated by Django 2.2.16 on 2020-10-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punishment',
            name='iden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punishment',
            name='pris',
            field=models.IntegerField(),
        ),
    ]
