name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2

    - name: Cache pre-commit
      uses: actions/cache@v2.0.0
      id: cache-precommit
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Cache Python files
      uses: actions/cache@v2
      with:
        path: |
          ~/.virtualenvs
          ~/.cache/pip
          ~/.cache/pypoetry
        key: poetry-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock', '**/pyproject.toml') }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Project Dependencies
      run: |
        poetry install --no-interaction --no-root
      if: steps.cache-poetry-envs.outputs.cache-hit != 'true'

    - name: Run commit hooks
      run: |
        cd backend
        touch .dev-reqs && touch .prod-reqs
        make hooks
